[package]
name = "td_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.1"
bevy_asset_loader = "0.22.0"

[workspace]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
